// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Realtime Database URL (required for regional DB; not set by older FlutterFire output).
  static const String _realtimeDbUrl =
      'https://login-4e779-default-rtdb.asia-southeast1.firebasedatabase.app';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBvWLiU46xhCLnE0c__2O7p-XVmwuZK9E',
    appId: '1:694615851522:web:ce8e75704f524c53db1d1b',
    messagingSenderId: '694615851522',
    projectId: 'login-4e779',
    authDomain: 'login-4e779.firebaseapp.com',
    storageBucket: 'login-4e779.firebasestorage.app',
    databaseURL: _realtimeDbUrl,
    measurementId: 'G-PGDD6CLQ02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDHDf8Lwt-i7VyXZE-LmMW-uu9iHfsoKM',
    appId: '1:694615851522:android:dc501dd587efbf78db1d1b',
    messagingSenderId: '694615851522',
    projectId: 'login-4e779',
    storageBucket: 'login-4e779.firebasestorage.app',
    databaseURL: _realtimeDbUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-MaK0xVMtYE7Xa3Nvzkp1KS1EfTI7cs',
    appId: '1:694615851522:ios:2c0a97ab1f00ef21db1d1b',
    messagingSenderId: '694615851522',
    projectId: 'login-4e779',
    storageBucket: 'login-4e779.firebasestorage.app',
    databaseURL: _realtimeDbUrl,
    iosBundleId: 'com.example.logon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV-MaK0xVMtYE7Xa3Nvzkp1KS1EfTI7cs',
    appId: '1:694615851522:ios:2c0a97ab1f00ef21db1d1b',
    messagingSenderId: '694615851522',
    projectId: 'login-4e779',
    storageBucket: 'login-4e779.firebasestorage.app',
    databaseURL: _realtimeDbUrl,
    iosBundleId: 'com.example.logon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBvWLiU46xhCLnE0c__2O7p-XVmwuZK9E',
    appId: '1:694615851522:web:d264a59867fb9ebddb1d1b',
    messagingSenderId: '694615851522',
    projectId: 'login-4e779',
    authDomain: 'login-4e779.firebaseapp.com',
    storageBucket: 'login-4e779.firebasestorage.app',
    databaseURL: _realtimeDbUrl,
    measurementId: 'G-EBF87WKWP9',
  );
}
